export { default as Dashboard } from '../pages/admin/dashboard/Dashboard'
export { default as AllProducts } from '../pages/allProducts/AllProducts'
export { default as Cart } from '../pages/cart/Cart'
export { default as Home } from '../pages/home/Home'
export { default as NoPage } from '../pages/nopage/NoPage'
export { default as Order } from '../pages/order/Order'
